---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: lists
  label: Lists
  create: all
  match: "**/*"
  templates:
  - hobbies
- type: directory
  path: general-copy
  label: General Copy
  create: all
  match: "**/*"
  templates:
  - copy
- type: directory
  path: projects
  label: Projects
  create: all
  match: "**/*"
  templates:
  - project
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
