---
label: Project
hide_body: false
fields:
- name: publish
  type: boolean
  label: Publish
  description: Default is unpublished for drafting purposes. Toggle this to signal
    that it is ready and available for rendering on the site.
- name: title
  type: text
  config:
    required: true
    min: 5
  label: Title
  description: Title or name of project.
- name: tags
  type: tag_list
  default: []
  label: Tags
  description: Tags, keywords on the tools. Separate by commas when entering. Try
    to keep to 4 or less.
- name: page_link
  type: text
  config:
    required: true
    min: 5
  label: Page link
  description: This will also be the what's known as the slug or the unique part of
    the URL. <br><br>The format should be the title in all lowercase and words split
    with '-' in between. Fx:<br><br>My project = my-project
- name: prototype_link
  type: text
  config:
    required: false
  label: Prototype link
  description: Full link to prototype.
- name: thumbnail
  type: file
  config:
    maxSize: 64
  label: Thumbnail
- name: hero_image_alt
  type: text
  config:
    required: false
  label: Hero Image Alt
  description: Description of Hero Image
- name: heroimageheight
  type: number
  label: Hero Image Height
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: hero_image_width
  type: number
  label: Hero Image Width
  description: ''
  default: 0
  required: true
  config:
    min: 
    max: 
    step: 
- name: offcenter
  type: boolean
  label: Offcenter
pages:
- projects/nicu-2-you.md
