---
label: Project
hide_body: false
fields:
- name: publish
  type: boolean
  label: Publish
  description: Default is unpublished for drafting purposes. Toggle this to signal
    that it is ready and available for rendering on the site.
- name: title
  type: text
  config:
    required: true
    min: 5
  label: Title
  description: Title or name of project.
- name: tags
  type: tag_list
  default: []
  label: Tags
  description: Tags, keywords on the tools. Separate by commas when entering. Try
    to keep to 4 or less.
- name: page_link
  type: text
  config:
    required: true
    min: 5
  label: Page link
  description: This will also be the what's known as the slug or the unique part of
    the URL. <br><br>The format should be the title in all lowercase and words split
    with '-' in between. Fx:<br><br>My project = my-project
- name: prototype_link
  type: text
  config:
    required: false
  label: Prototype link
  description: Full link to prototype.
- name: duration
  type: number
  label: Duration
  description: Duration of project in number of weeks
  default: 1
  required: true
  config:
    min: 
    max: 
    step: 1
- name: hero_image
  type: file
  config:
    maxSize: 1
  description: This is the main photo to be used in previews and hero style sections.
  label: Cover photo
- name: gallery
  type: image_gallery
  config: {}
  label: Gallery
  description: Load photos here that will be used. Then insert them by referencing
    the gallery.
pages:
- projects/nicu-2-you.md
- projects/organic-ecommerce-website.md
